sonar.projectKey=linkhub
sonar.projectName=LinkHub
sonar.projectVersion=0.1.3

# Define a raiz para busca de fontes e testes
sonar.sources=.
sonar.tests=.

# Padrões para incluir arquivos de código e arquivos de teste
sonar.sources.inclusions=**/*.py
sonar.test.inclusions=**/test_*.py,**/tests_*.py,**/tests.py

# Arquivos e pastas que NÃO devem ser analisados como código principal
sonar.exclusions=\
    venv/**,\
    .venv/**,\
    **/venv/**,\
    .pytest_cache/**,\
    **/__pycache__/**,\
    **/migrations/**,\
    **/tests.py,\
    **/test_*.py,\
    docs/**,\
    sigarte/**,\
    **/static/**,\
    **/templates/**,\
    **/admin.py,\
    **/__init__.py,\
    manage.py

# Arquivos e pastas que NÃO devem ser analisados como testes (ignora bibliotecas da venv)
sonar.test.exclusions=\
    venv/**,\
    .venv/**,\
    **/venv/**,\
    .pytest_cache/**,\
    **/__pycache__/**

# Codificação e Relatório de Cobertura
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml